# Generated by Django 4.2.28 on 2026-02-12 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_cliente', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('date_rdv', models.DateTimeField()),
                ('message', models.TextField(blank=True)),
                ('prestation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.prestation')),
            ],
        ),
    ]
