# Generated by Django 4.2.28 on 2026-02-12 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestation',
            name='prix',
        ),
        migrations.AddField(
            model_name='prestation',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='prestation',
            name='options_json',
            field=models.TextField(blank=True, default='{}'),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='option_choisie',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='prix_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
